# Generated by Django 3.1.6 on 2021-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=254, verbose_name='구글로그인 아이디')),
                ('email', models.EmailField(max_length=254, verbose_name='사용자 이메일')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
            ],
        ),
    ]
