# Generated by Django 3.1.6 on 2021-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210221_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='peer_id',
            field=models.CharField(max_length=254, null=True, verbose_name='피어 id'),
        ),
        migrations.AddField(
            model_name='user',
            name='room_id',
            field=models.IntegerField(null=True, verbose_name='방번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(max_length=50, null=True, verbose_name='유저타입'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='사용자 이메일'),
        ),
    ]
