# Generated by Django 3.1.6 on 2021-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210221_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default', max_length=254, null=True, unique=True, verbose_name='사용자 이메일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.CharField(default='default', max_length=254, null=True, verbose_name='구글로그인 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='peer_id',
            field=models.CharField(default='default', max_length=254, null=True, verbose_name='피어 id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='default', max_length=50, null=True, verbose_name='유저타입'),
        ),
    ]
