# Generated by Django 3.1.6 on 2021-02-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210222_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@naver.com', max_length=254, null=True, verbose_name='사용자 이메일'),
        ),
    ]
