# Generated by Django 3.1.6 on 2021-02-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210223_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room_id',
            field=models.IntegerField(default=0, null=True, verbose_name='방번호'),
        ),
    ]
