# Generated by Django 3.1.6 on 2021-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='nickname', max_length=50, verbose_name='게스트 이름')),
                ('room_uuid', models.CharField(default='room_uuid', max_length=100, verbose_name='방 고유 아이디')),
                ('user_uuid', models.CharField(default='user_uuid', max_length=100, verbose_name='게스트 고유 아이디')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='room_name', max_length=100, verbose_name='방 이름')),
                ('room_uuid', models.CharField(default='room_uuid', max_length=100, verbose_name='방 고유 아이디')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
