# Generated by Django 3.1.6 on 2021-02-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
    ]
